name: Deployment Workflow

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          if ! pgrep mongod; then
            mongod
            echo "started mongodb!"
          fi
      # run: |
      #   mkdir -p ~/.ssh
      #   sshpass -v -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@"${{ secrets.VPS_IP }}" << EOF
      #     if ! pgrep mongod; then
      #       mongod
      #       echo "started mongodb!"
      #     fi
      #     echo pgrep mongod
      #     echo ! pgrep mongod
      #     echo !$(pgrep mongod)
      #     echo 'trying rm..'
      #     rm -rf /var/www/html/date-night-mevn/
      #     echo 'exiting first block'
      #   EOF
      #   scp -r . "${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/var/www/html/date-night-mevn/"
      #   echo 'tried scp'
      #   sshpass -v -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@"${{ secrets.VPS_IP }}" << EOF
      #     cd /var/www/html/date-night-mevn/
      #     npm ci
      #     npm run build
      #   EOF

    # - name: Check for .env.production file
    #   run: |
    #     # Add code to check if .env.production file is present in the client directory
    #     # If it's not present, exit the workflow
